name: quick_datetime_picker
description: "A datetime picker package with option to use a single datetime picker or a datetime range picker."
version: 1.0.5
repository: "https://github.com/strattonn/QuickDateTimePicker"
homepage: ""

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
